receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "otel-collector:4317"
      http:
        endpoint: "otel-collector:4318"

exporters:
  debug:  # Data sources: traces, metrics, logs
    # verbosity: basic
    verbosity: detailed

  file:
    path: /logs/logs.json

  prometheus:  # Data sources: metrics
    endpoint: "otel-collector:7070"

  otlp/jaeger:  # Data sources: traces
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  otlp/profiles:
    endpoint: http://pyroscope:4040
    tls:
      insecure: true

service:
  pipelines:
    # logs:
      # receivers: [otlp]
      # exporters: [file, debug]
    # metrics:
      # receivers: [otlp]
      # exporters: [prometheus, debug]
    # traces:
      # receivers: [otlp]
      # exporters: [otlp/jaeger, debug]
    profiles:
      receivers: [otlp]
      exporters: [otlp/profiles, debug]


# yaml-language-server: $schema=https://raw.githubusercontent.com/srikanthccv/otelcol-jsonschema/main/schema.json
